project:
  type: website
  output-dir: ../docs # GitHub Pages
  preview:
    port: 3000
    browser: true

website:
  repo-url: https://github.com/maple60/morphometrics-tool
  repo-subdir: website
  repo-actions: [edit, source, issue]
  title: "Leaf Shape Analysis Tool"
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/maple60/morphometrics-tool
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
  sidebar:
    style: "docked"
    contents:
      - section: "Basics"
        contents:
        - text: "Preparation"
          href: preparation.qmd
        - text: "Usage"
          href: usage.qmd
        - text: "Analysis"
          href: analysis.qmd
      - section: "Appendix"
        contents:
        - text: "Related Tools and Frameworks"
          href: related_tools.qmd
  search: 
    location: sidebar
    type: textbox
  page-footer:
    left: "© 2025 Leaf Shape Analysis Tool"
    right: "Built with Quarto"

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    number-sections: false
    link-external-icon: true
    link-external-newwindow: true
